//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_CW2_00003905.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
        public string userName { get; set; }
        public string requestIP { get; set; }
        public string controllerName { get; set; }
        public string actionName { get; set; }
        public string requestType { get; set; }
        public string requestParams { get; set; }
    }
}
